include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    avoid_relative_lib_imports: true
    library_private_types_in_public_api: true