name: Tag New Version

on:
  push:
    branches: [ master ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extrair versão do pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep "^version:" pubspec.yaml | cut -d " " -f 2)
          echo "Versão extraída: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Criar tag e fazer push
        run: |
          git tag "v${{ steps.get_version.outputs.version }}"
          git push origin "v${{ steps.get_version.outputs.version }}"
